"""Prompt Builder for CyberRAG."""

import logging

logger = logging.getLogger(__name__)

DEFAULT_SYSTEM_TEMPLATE = (
    "Answer only using the supplied context. "
    "Never fabricate CVEs. "
    "State when information is unavailable. "
    "Remain concise and technical. "
    "Preserve cybersecurity terminology."
)

DEFAULT_USER_TEMPLATE = "Question:\n\n{query}\n\nContext:\n\n{context}\n\nAnswer:"

def build_prompt(
    query: str,
    context: str,
    system_template: str | None = None,
    user_template: str | None = None,
    max_size: int | None = None,
) -> dict[str, str]:
    """Construct deterministic prompts for the language model.

    Parameters
    ----------
    query : str
        The original user question.
    context : str
        Structured context block generated by the Context Builder.
    system_template : str | None, optional
        Custom template for the system prompt.
    user_template : str | None, optional
        Custom template for the user prompt. Must contain {query} and {context} placeholders.
    max_size : int | None, optional
        Maximum allowed total size of the generated prompts.

    Returns
    -------
    dict
        A dictionary containing the 'system' and 'user' prompts.

    Raises
    ------
    TypeError
        If `query` or `context` are not strings.
    ValueError
        If `query` or `context` are empty strings, or if the generated prompts exceed `max_size`.
    """
    if not isinstance(query, str) or not isinstance(context, str):
        raise TypeError("Query and context must be strings.")

    if not query.strip():
        raise ValueError("Query cannot be empty.")

    if not context.strip():
        raise ValueError("Context cannot be empty.")

    system_prompt = system_template if system_template is not None else DEFAULT_SYSTEM_TEMPLATE
    user_template_str = user_template if user_template is not None else DEFAULT_USER_TEMPLATE

    user_prompt = user_template_str.format(query=query, context=context)

    total_size = len(system_prompt) + len(user_prompt)

    if max_size is not None and total_size > max_size:
        raise ValueError(f"Generated prompt size ({total_size}) exceeds maximum allowed size ({max_size}).")

    logger.info(
        f"Prompt generated successfully. "
        f"Context Size={len(context)}, "
        f"System Prompt Size={len(system_prompt)}, "
        f"User Prompt Size={len(user_prompt)}, "
        f"Total Prompt Size={total_size}"
    )

    return {
        "system": system_prompt,
        "user": user_prompt
    }
