"""Response Formatter for CyberRAG."""

import logging
from typing import Any

logger = logging.getLogger(__name__)

def format_response(
    llm_response: str,
    retrieved_documents: list[dict[str, Any]]
) -> dict[str, Any]:
    """Convert the raw LLM response into a structured, user-facing format.

    Parameters
    ----------
    llm_response : str
        The raw text response generated by the LLM.
    retrieved_documents : list of dict
        The documents returned by the retrieval pipeline used as context.

    Returns
    -------
    dict
        A structured dictionary containing the formatted answer, cited sources,
        and source metadata.

    Raises
    ------
    ValueError
        If the LLM response is empty or if retrieved documents are missing/empty.
    """
    logger.info("Starting response formatting.")

    if not llm_response or not llm_response.strip():
        logger.error("Empty LLM response provided.")
        raise ValueError("LLM response cannot be empty.")

    if not retrieved_documents:
        logger.error("Empty or missing retrieved documents provided.")
        raise ValueError("Retrieved documents cannot be empty or missing.")

    sources = []
    metadata_list = []

    for doc in retrieved_documents:
        # Require 'id' as a minimum valid metadata field for a source
        if "id" not in doc:
            logger.error("Invalid metadata: Document missing 'id'.")
            raise ValueError("Invalid metadata: Document must contain an 'id'.")

        cve_id = doc["id"]
        sources.append(cve_id)

        # Extract metadata
        doc_metadata = doc.get("metadata", {})

        # Retrieve properties matching required fields: Severity, CVSS, Published date
        severity = doc.get("severity") or doc_metadata.get("severity")
        cvss = doc_metadata.get("cvss_score")
        published = doc_metadata.get("publication_year") or doc_metadata.get("published_date")

        meta = {
            "id": cve_id,
        }
        if severity is not None:
            meta["severity"] = severity
        if cvss is not None:
            meta["cvss"] = cvss
        if published is not None:
            meta["published"] = published

        metadata_list.append(meta)

    if not sources:
        logger.error("Empty source list after processing documents.")
        raise ValueError("Empty source list: No valid sources found in retrieved documents.")

    formatted_text = "Answer\n\n"
    formatted_text += llm_response.strip()
    formatted_text += "\n\nSources\n\n"

    # Deduplicate sources preserving order
    seen = set()
    unique_sources = []
    for s in sources:
        if s not in seen:
            unique_sources.append(s)
            seen.add(s)

    for source in unique_sources:
        formatted_text += f"- {source}\n"

    formatted_text = formatted_text.strip()

    logger.info(f"Response formatting completed. Cited sources: {len(unique_sources)}. Response size: {len(formatted_text)} chars.")

    return {
        "answer": llm_response.strip(),
        "sources": unique_sources,
        "metadata": metadata_list,
        "formatted_text": formatted_text,
        "confidence": None  # Placeholder if confidence becomes available from LLM later
    }
